# Generated by Django 6.0.7 on 2026-07-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('FURNITURE_TYPES', models.CharField(choices=[('CHAIR', 'Chair'), ('TABLE', 'Table'), ('BED', 'Bed'), ('SOFA', 'Sofa'), ('WARDROBE', 'Wardrobe'), ('CABINET', 'Cabinet / Storage'), ('DINING', 'Dining Set'), ('OFFICE', 'Office Desk')])),
                ('description', models.TextField(max_length=500)),
                ('img', models.ImageField(upload_to='')),
            ],
        ),
    ]
