# Generated by Django 6.0.7 on 2026-07-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='img',
            field=models.ImageField(upload_to='stocks/'),
        ),
    ]
